# A YAML file
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: invalid-certificate-data
    server: https://k8s.markwaite.net
  name: my-cluster
contexts:
- context:
    cluster:  k8s
    user:  mwaite
  name:  k8s-mwaite
current-context: k8s-mwaite
kind: Config
preferences: {}
users:
- name:  mwaite
  user:
    token: not-so-secret-token